Repository accordproject/models, pull requests merged in 2019-10, with the labels that each got.

#61 docs(README): center ap logo and title
  README.md
Labels: Hacktoberfest, Type: Documentation 📝

#62 docs(README): fix typos
  README.md
Labels: Hacktoberfest, Type: Documentation 📝

#63 fix(views): correct typo and update links
  views/index.njk
Labels: Hacktoberfest, Type: Documentation 📝

#64 docs(README): add license and slack badges
  README.md
Labels: Hacktoberfest, Type: Documentation 📝

#58 docs(DEVELOPERS): init file - I57
  DEVELOPERS.md
Labels: Hacktoberfest, Type: Documentation 📝

#71 fix(CONTRIBUTING): broken coc link - I70
  CONTRIBUTING.md
Labels: Difficulty: Starter, Hacktoberfest

#73 docs(*): update markdown files and fix typos - I257
  CONTRIBUTING.md
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#72 feat(docs): add ecosystem table
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#74 chore(gitignore): add thumbs.db
  .gitignore
Labels: Difficulty: Starter, Hacktoberfest

#89 fix(README): typo - I88
  README.md
Labels: Difficulty: Starter, Hacktoberfest

#81 feat(views): utilize AP logo - I80
  assets/images/A-MARK-ACCORDPROJECT-ONELINE-white.svg
  views/page.njk
Labels: Difficulty: Starter, Hacktoberfest, Type: Enhancement ✨
